name: Test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: iwata-n/android-project-healthcheck@main
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle
          path: checkstyle_result.txt
